### ISSUE TITLE
Maximum Number of Charachters in the payload

### ISSUE THREAD

**Issue by helcioburd** [rossmann-engineering/CoDeSys-MQTT-library#1]
Hello,
I am currently testing this library (v. 3.5.13.26) and it works really well so far with one minor issue. One of them has to do with the maximum number of characters in the payload (to publish). I was expecting to be able to publish a maximum of 255 with this library. However, the **maximum I can send is 114**. If I try to send more than 114, the broker won't receive anything at all and the library won't receive anything it subscribed for either.
Thank you

**Comment by WernerPixner** [comment]
the error is in the FB_CalculateRemainingLength function of the Library
Solution:
substitute line 8 
		bEncodedByte := (bEncodedByte AND 128);
with this
                bEncodedByte := (bEncodedByte OR 128);

**Comment by helcioburd** [comment]
Hi Werner,
Your solution works!!!
Thank You
